
export const businessData = {
  name: 'The Gourmet Place',
  logo: 'https://picsum.photos/seed/logo/100/100',
};

export const events = [
  {
    id: '1',
    name: 'Jazz Night',
    description: 'Enjoy a relaxing evening with live jazz music featuring some of the best local artists. The night will be filled with smooth melodies and a great atmosphere. Perfect for a date night or a night out with friends. Full bar and a special cocktail menu will be available.',
    datetime: '2023-11-15T19:00:00',
    imageUrl: 'https://picsum.photos/seed/event1/600/400',
    imageHint: 'jazz band',
    active: true,
    organizers: 'The Velvet Note Club, City Jazz Association',
    terms: 'No outside food or drinks allowed.',
  },
  {
    id: '2',
    name: 'Taco Tuesday',
    description: 'Special discounts on all tacos and margaritas.',
    datetime: '2023-11-21T17:00:00',
    imageUrl: 'https://picsum.photos/seed/event2/600/400',
    imageHint: 'tacos food',
    active: false,
    organizers: '',
    terms: '',
  },
  {
    id: '3',
    name: 'Wine Tasting',
    description: 'Explore a selection of fine wines from around the world.',
    datetime: '2023-12-01T18:30:00',
    imageUrl: 'https://picsum.photos/seed/event3/600/400',
    imageHint: 'wine glasses',
    active: true,
    organizers: 'Global Vintners',
    terms: 'Must be 21 or older to participate.',
  },
];

export const menu = {
  categories: [
    { name: 'Appetizers', imageUrl: 'https://picsum.photos/seed/cat1/300/200', imageHint: 'appetizers food', description: 'Light bites to start your meal.' },
    { name: 'Main Course', imageUrl: 'https://picsum.photos/seed/cat2/300/200', imageHint: 'main course', description: 'Hearty and satisfying main dishes.' },
    { name: 'Desserts', imageUrl: 'https://picsum.photos/seed/cat3/300/200', imageHint: 'dessert', description: 'Sweet treats to finish.' },
    { name: 'Beverages', imageUrl: 'https://picsum.photos/seed/cat4/300/200', imageHint: 'beverages', description: 'Cool and refreshing drinks.' },
    { name: 'Soups', imageUrl: 'https://picsum.photos/seed/cat5/300/200', imageHint: 'soup bowl', description: 'Warm and comforting soups.' },
    { name: 'Salads', imageUrl: 'https://picsum.photos/seed/cat6/300/200', imageHint: 'fresh salad', description: 'Fresh and healthy salads.' },
    { name: 'Seafood', imageUrl: 'https://picsum.photos/seed/cat7/300/200', imageHint: 'seafood platter', description: 'From the ocean to your plate.' },
    { name: 'Breads', imageUrl: 'https://picsum.photos/seed/cat8/300/200', imageHint: 'artisan bread', description: 'Freshly baked breads.' },
  ],
  items: [
    {
      id: '1',
      name: 'Margherita Pizza',
      category: 'Main Course',
      price: '250',
      type: 'veg' as const,
      description:
        'A classic pizza with fresh mozzarella, tomatoes, and basil.',
      kcal: '750',
      imageUrl: 'https://picsum.photos/seed/item1/400/300',
      imageHint: 'margherita pizza',
      tags: ['bestseller'],
    },
    {
      id: '2',
      name: 'Chicken Burger',
      category: 'Main Course',
      price: '180',
      type: 'non-veg' as const,
      description:
        'A juicy chicken patty with lettuce, tomato, and our special sauce.',
      kcal: '550',
      imageUrl: 'https://picsum.photos/seed/item2/400/300',
      imageHint: 'chicken burger',
      tags: [],
    },
    {
      id: '3',
      name: 'Caesar Salad',
      category: 'Salads',
      price: '150',
      type: 'veg' as const,
      description: 'Crisp romaine lettuce with croutons and parmesan cheese.',
      kcal: '350',
      imageUrl: 'https://picsum.photos/seed/item3/400/300',
      imageHint: 'caesar salad',
      tags: ['healthy'],
    },
    {
      id: '4',
      name: 'Chocolate Lava Cake',
      category: 'Desserts',
      price: '120',
      type: 'veg' as const,
      description: 'Warm chocolate cake with a gooey molten center.',
      kcal: '450',
      imageUrl: 'https://picsum.photos/seed/item4/400/300',
      imageHint: 'lava cake',
      tags: ['bestseller'],
    },
    {
      id: '5',
      name: 'Mojito',
      category: 'Beverages',
      price: '90',
      type: 'veg' as const,
      description: 'A refreshing mix of mint, lime, and soda.',
      kcal: '150',
      imageUrl: 'https://picsum.photos/seed/item5/400/300',
      imageHint: 'mojito drink',
      tags: [],
    },
    {
      id: '6',
      name: 'Tomato Soup',
      category: 'Soups',
      price: '110',
      type: 'veg' as const,
      description: 'Creamy tomato soup served with croutons.',
      kcal: '200',
      imageUrl: 'https://picsum.photos/seed/item6/400/300',
      imageHint: 'tomato soup',
      tags: [],
    },
    {
      id: '7',
      name: 'Grilled Salmon',
      category: 'Seafood',
      price: '450',
      type: 'non-veg' as const,
      description: 'Perfectly grilled salmon fillet with a lemon-dill sauce.',
      kcal: '600',
      imageUrl: 'https://picsum.photos/seed/item7/400/300',
      imageHint: 'grilled salmon',
      tags: ['healthy'],
    },
    {
      id: '8',
      name: 'Garlic Bread',
      category: 'Breads',
      price: '90',
      type: 'veg' as const,
      description: 'Toasted bread with garlic butter and herbs.',
      kcal: '300',
      imageUrl: 'https://picsum.photos/seed/item8/400/300',
      imageHint: 'garlic bread',
      tags: [],
    },
  ],
};
