import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {SidebarProvider} from '@/components/ui/sidebar';
import {AppSidebar} from '@/components/layout/sidebar';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({subsets: ['latin'], variable: '--font-inter'});

export const metadata: Metadata = {
  title: 'QRLive Menu',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} h-screen overflow-hidden`}>
        <div className="flex h-full">
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 overflow-y-auto bg-gray-100 p-4">
              {children}
            </main>
          </SidebarProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
