
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { FirebaseClientProvider } from '@/firebase';
import { GoogleAnalytics } from '@/components/GoogleAnalytics';
import { Suspense } from 'react';

const inter = Inter({subsets: ['latin'], variable: '--font-inter'});

export const metadata: Metadata = {
  title: 'QRLive Menu',
  description: 'Generated by Firebase Studio',
  manifest: '/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
      </head>
      <body className={`${inter.variable}`}>
        <FirebaseClientProvider>
          <Suspense>
            <GoogleAnalytics />
          </Suspense>
          {children}
        </FirebaseClientProvider>
        <Toaster />
        <script
          id="razorpay-checkout-js"
          src="https://checkout.razorpay.com/v1/checkout.js"
        ></script>
      </body>
    </html>
  );
}
