
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { FirebaseClientProvider } from '@/firebase';
import { GoogleAnalytics } from '@/components/GoogleAnalytics';
import { Suspense } from 'react';

const inter = Inter({subsets: ['latin'], variable: '--font-inter'});

export const metadata: Metadata = {
  title: 'QRLive Menu',
  description: 'Generated by Firebase Studio',
  manifest: '/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
          <meta name="application-name" content="QRLive Menu" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="default" />
          <meta name="apple-mobile-web-app-title" content="QRLive" />
          <meta name="format-detection" content="telephone=no" />
          <meta name="mobile-web-app-capable" content="yes" />
          <meta name="theme-color" content="#0B2447" />
      </head>
      <body className={`${inter.variable}`}>
        <FirebaseClientProvider>
          <Suspense>
            <GoogleAnalytics />
          </Suspense>
          {children}
        </FirebaseClientProvider>
        <Toaster />
        <script
          id="razorpay-checkout-js"
          src="https://checkout.razorpay.com/v1/checkout.js"
        ></script>
      </body>
    </html>
  );
}
